### ISSUE TITLE
Issues in V2 of software for photo exposure and focus

### ISSUE THREAD

**Issue by Hubertszcz** [Digital-Naturalism-Laboratories/Mothbox#9]
V1 was deployed in Venao Hills between 29.2.24 and 13.3.24, V2 was deployed in the same location between 16.3.24 and 30.3.24.

- V1 produced very blue photos. This has mostly not been corrected in V2, though interestingly some of the photos (I can't discern a pattern) are colour-corrected.
- V1 had photos with the background overexposed (but most of the moths well exposed) for the first few hours, and dimmed down to a bit underexposed by the end of the first night of deployment. The second day starts underexposed and goes down from there. For V2, the photos start underexposed from the beginning, and still dim by the end of the first night. The second night is all dim ending in difficult to use level of underexposure.
- Interestingly, the relative dimness of the UV and ring lights behaves differently between V1 and V2. In V1 the UV light dies well before the end of night 2, but the ring lights stay usable well after the UV light dies. In V2, the ring lights dim much faster, and get very dim before the UV light goes out.
- The focus is noticeably worse in V2, overall, and especially further away from the center. 

We need higher exposure, better focus, and more consistent color correction.

**Comment by quitmeyer** [comment]
auto focuses and auto calibrates every 6 mins. should fix this
